PROGRAM CONTOH_BUBBLESORT;
USES CRT;
VAR
NILAI : ARRAY[1..100] OF INTEGER;
I,N,J,T:INTEGER;
BEGIN
CLRSCR;
WRITE('JUMLAH DATA : ');READLN(N);
FOR I:=1 TO N DO
BEGIN
WRITE('MASUKKAN NILAI KE ',I,' : ');READLN(NILAI[I]);
END;
CLRSCR;
FOR I:=1 TO N-1 DO
BEGIN
FOR J:=I+1 TO N DO
BEGIN
IF NILAI[I]>NILAI[J] THEN
BEGIN
T:=NILAI[I];
NILAI[I]:=NILAI[J];
NILAI[J]:=T;
END;
END;
END;
WRITELN;
WRITELN('NILAI YANG TELAH DIURUTKAN ADALAH :');
FOR I:=1 TO N DO
WRITE(NILAI[I],' ');
READLN;
END.